<?php $this->inlineScript()->prependFile($this->basePath('js/cars/index.js')); ?>
<?php $this->inlineScript()->prependFile($this->basePath('js/sweetalert/sweetalert.min.js')); ?>

<?php $this->headLink()->prependStylesheet($this->basePath('css/sweetalert/sweetalert.css')); ?>


<div id="cars">
	<button class="btn btn-primary" v-on:click="generateList">Сгенерировать список</button>
	<br><br>
	<table class="table table-stripped">
		<tr>
			<th>ID</th>
			<th>Марка</th>
			<th>Модель</th>
			<th>Статус</th>
			<th>Комплектация</th>
			<th>Мощность</th>
			<th>Цвет</th>
			<th>Фото</th>
			<th>Цена</th>
		</tr>
		<tr v-for="car in cars">
			<td>{{ car.id }}</td>
			<td>{{ car.brand }}</td>
			<td>{{ car.model }}</td>
			<td><span class="label" :class="getStatusLabelClass(car.status)">{{ getStatusName(car.status) }}</span></td>
			<td>{{ car.config }}</td>
			<td>{{ car.power }}</td>
			<td>{{ car.color }}</td>
			<td>{{ car.image }}</td>
			<td>{{ formatPrice(car.price) }} р.</td>
		</tr>
	</table>
</div>